name: Push Development

on:
    schedule:
        - cron: '15 * * * *'

jobs:
    test_schedule:
        runs-on: ubuntu-latest
        env:
            REDASH_API_KEY: ${{ secrets.REDASH_API_KEY }}
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: execute python script
              run: python3 ./cron/checkScheduler.py
